apiVersion: apps/v1
kind: Service
metadata:
  name: nginx-service
  lables:
    app: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
